version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  test:
    docker:
      - image: cimg/ruby:3.0.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundler version
          command: gem install bundler:2.5.6
      - ruby/bundle-install
      - run:
          name: Run rspec
          command: bundle exec rspec spec/

  rubocop:
    docker:
      - image: cimg/ruby:3.0.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundler version
          command: gem install bundler:2.5.6
      - ruby/bundle-install
      - run:
          name: Run rubocop
          command: bundle exec rubocop

workflows:
  build_accept:
    jobs:
      - rubocop
      - test
